#version: '3.8'
# Deploys MongoDB with customization scripts and container with Mongo client
# https://fabianlee.org/2018/05/20/docker-using-docker-compose-to-link-a-mongodb-server-and-client/
#
# usage:
# sudo docker-compose build
# sudo docker-compose up


services:
  my-mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: my-mongodb
    ports:
      - 27017:27017
    restart: always
    #environment:
      #- MONGO_INITDB_DATABASE=test
      #- MONGO_INITDB_ROOT_USERNAME=mongoadmin
      #- MONGO_INITDB_ROOT_PASSWORD=Pwd!5382*
    volumes:
      # named volumes
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    networks:
      - mongo_net
    
volumes:
  # default dir on Ubuntu: /var/lib/docker/volumes
  mongodb-data:
  mongodb-config:

networks:
  mongo_net:
    driver: bridge